ARG RUBY_VERSION=2.3.1
FROM ruby:${RUBY_VERSION}

#ARG BUNDLER_VERSION=2.3
ARG UNAME=uname
ARG UID=1000
ARG GID=1000

LABEL maintainer="dla-staff@umich.edu"

RUN apt-get update -yqq && apt-get upgrade -yqq
RUN apt-get install -yqq --no-install-recommends \
  vim

RUN gem install rubygems-update
RUN update_rubygems
RUN gem update --system

#RUN gem install bundler:${BUNDLER_VERSION}
RUN gem install bundler

RUN groupadd -g ${GID} -o ${UNAME}
RUN useradd -m -d /app -u ${UID} -g ${GID} -o -s /bin/bash ${UNAME}
RUN mkdir -p /gems && chown ${UID}:${GID} /gems

USER $UNAME

ENV BUNDLE_PATH /gems

WORKDIR /app

COPY --chown=${UID}:${GID} . /app
#RUN bundle _${BUNDLER_VERSION}_ install
RUN bundle install

#CMD ["tail", "-f", "/dev/null"]
CMD ["sleep", "infinity"]


